sudo: required
services:
  - docker

before_install:
  - docker build -t karnpini/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true karnpini/react-test npm test

after_success:
  - docker build -t karnpini/multi-client ./client
  - docker build -t karnpini/multi-nginx ./nginx
  - docker build -t karnpini/multi-server ./server
  - docker build -t karnpini/multi-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push karnpini/multi-client
  - docker push karnpini/multi-nginx
  - docker push karnpini/multi-server
  - docker push karnpini/multi-worker